[package]
name = "papaya"
version = "0.1.0"
edition = "2021"

[dependencies]
atomic-wait = "1.1.0"
seize = "0.3.2"

[dev-dependencies]
rand = "0.8"
dashmap = "5.5"
criterion = "0.5"

[[bench]]
name = "compare"
harness = false

[[bench]]
name = "misc"
harness = false
