[package]
name = "the-one"
version = "0.1.0"
edition = "2021"

[dependencies]
atomic-wait = "1.1.0"
num_cpus = "1.13.1"
once_cell = "1.16.0"
parking_lot_core = "0.9.7"
tracing = { version = "0.1.35", optional = true }
